### PR TITLE
FIX Check canView() permission before rendering BaseElements

### LINKED ISSUE #253: canView permissions aren’t checked on front-end
I’ve implemented `canView()` permissions on a per-element basis (mimicking `CanViewType` and `ViewerGroups` from `SiteTree`), out of the box these permissions aren’t checked before rendering.

It’s easy enough to implement these checks myself, just struck me as worth considering :)

### PR DESCRIPTION
**Pull request by raissanorth**
Fixes #253 by checking canView() permissions before rendering BaseElements.

### CODE REVIEW

File: src/Controllers/ElementController.php [hunk 1]
```diff
@@ -68,10 +68,14 @@ public function getElement()
...
      * {@link ElementController}.
      *
-     * @return string HTML
+     * @return null|string HTML
      */
     public function forTemplate()
     {
+        if (!$this->element->canView()) {
+            return null;
+        }
```
Comment (robbieaverill) [inline src/Controllers/ElementController.php]: I think I'd rather put `<% if $canView %>` checks into the template, e.g. around ElementHolder.ss

If continuing with this approach we'd need to update the unit test that's failing

Comment (kinglozzer) [reply src/Controllers/ElementController.php]: We’ve had issues in core before, I think with `Versioned::doPublish()`, where people bypass permission checks intentionally (e.g. CLI publishes and stuff like that) and expect things to work. I think this could fall into that category - if I call `$html = $element->forTemplate()` directly, I wouldn’t expect `null`.

I’d suggest filtering the elements in `ElementalArea::ElementControllers()`, something like

```php
$items = $this->Elements()->filterByCallback(function (BaseElement $item) {
    return $item->canView();
});
```

**Comment by raissanorth** [comment]
Alrighty, reverted my prior changes and went with @kinglozzer's approach - thanks very much for your input!

File: tests/ElementalAreaTest.php [hunk 2]
```diff
@@ -33,6 +33,19 @@ public function testElementControllers()
...
+    public function testViewPermissionsAreChecked()
+    {
+
+        $area = $this->objFromFixture(ElementalArea::class, 'area2');
+        $controllers = $area->ElementControllers();
+        $elements = $area->Elements();
+
+        $this->assertEquals(1, $controllers->count(),
+            'Should be one controller only, since one of the elements is not viewable');
+        $this->assertEquals(2, $elements->count());
```
Comment (robbieaverill) [inline tests/ElementalAreaTest.php]: Minor: you can use assertCount(2, $elements)

File: tests/Src/TestElement.php [hunk 3]
```diff
@@ -19,4 +20,9 @@ public function getType()
     {
         return 'A test element';
     }
+
+    public function canView($member = null)
+    {
+        return parent::canView($member) && $this->Viewable;
```
Comment (robbieaverill) [inline tests/Src/TestElement.php]: This is testing the behaviour of a stub. Perhaps instead it could implement a real world permission check like “is admin”, then you can log in as a content author in the tests and assert that it’s not viewable

**Comment by robbieaverill** [comment]
Follow up at #265
